using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace Manhunters
{

    public class ManhunterPartyComponent : WarPartyComponent
    {
        [CachedData]
        private TextObject _cachedName;

        [SaveableField(30)]
        private Hero _leader;

        public override Hero PartyOwner => Owner;

        [SaveableProperty(50)]
        public TextObject _customName { get; set; }

        public override TextObject Name => _cachedName ?? (_cachedName = ((Owner != null) ? GetPartyName() : new TextObject("{=!}unnamedMobileParty")));

        public override Settlement HomeSettlement => Owner.HomeSettlement;

        [SaveableProperty(20)]
        public Hero Owner
        {
            get;
            private set;
        }

        public override Hero Leader => _leader;

        [SaveableProperty(30)]
        public int Gold { get; set; }

        public int MinPartySize { get; set; } = 5;
        public int MaxPartySize { get; set; } = 25;
        public enum ManhunterPartyState
        {
            Invalid,
            GoingToSettlementForSellingPrisoners,
            GoingToSettlementToBuyFood,
            EngagingToBandits,
            SellingPrisoners,
            BuyingFood
        }

        public TroopRoster potentialPrisoners;
        public ManhunterPartyState State { get; set; } = ManhunterPartyState.Invalid;

        internal static void AutoGeneratedStaticCollectObjectsManhunterPartyComponent(object o, List<object> collectedObjects)
        {
            ((ManhunterPartyComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
        }

        protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
            base.AutoGeneratedInstanceCollectObjects(collectedObjects);
            collectedObjects.Add(_leader);
            collectedObjects.Add(Owner);
        }
    
        

        internal static object AutoGeneratedGetMemberValueOwner(object o)
        {
            return ((ManhunterPartyComponent)o).Owner;
        }

        internal static object AutoGeneratedGetMemberValue_leader(object o)
        {
            return ((ManhunterPartyComponent)o)._leader;
        }

        public static MobileParty CreateManhunterParty(string stringId, Hero hero, Vec2 position, float spawnRadius, Settlement spawnSettlement, Hero partyLeader)
        {
            return MobileParty.CreateParty(hero.CharacterObject.StringId + stringId, new ManhunterPartyComponent(hero, partyLeader), delegate (MobileParty mobileParty)
            {
                ((ManhunterPartyComponent)mobileParty.PartyComponent).InitializeManhunterPartyProperties(mobileParty, position, spawnRadius, spawnSettlement);
                
            });
        }

        protected internal ManhunterPartyComponent(Hero owner, Hero leader)
        {
            Owner = owner;
            _leader = leader;
            potentialPrisoners = TroopRoster.CreateDummyTroopRoster();
        }      

        internal void ChangePartyOwner(Hero owner)
        {
            ClearCachedName();
            Owner = owner;
        }

        public override void ChangePartyLeader(Hero newLeader)
        {
            _leader = newLeader;
            ClearCachedName();
        }

        public override void ClearCachedName()
        {
            _cachedName = null;
        }

        private TextObject GetPartyName()
        {
            TextObject textObject = new TextObject("manhunter party");
            textObject.SetCharacterProperties("TROOP", Owner.CharacterObject);    
            return textObject;
        }

        private void InitializeManhunterPartyProperties(MobileParty mobileParty, Vec2 position, float spawnRadius, Settlement spawnSettlement)
        {
            mobileParty.AddElementToMemberRoster(Owner.CharacterObject, 1, insertAtFront: true);
            mobileParty.ActualClan = Owner.Clan;

            TroopRoster memberRoster = new TroopRoster(mobileParty.Party);
            CharacterObject troop = MBObjectManager.Instance.GetObject<CharacterObject>("manhunter_character");
            memberRoster.AddToCounts(troop, MBRandom.RandomInt(MinPartySize, MaxPartySize));

            TroopRoster prisonerRoster = new TroopRoster(mobileParty.Party);

            mobileParty.InitializeMobilePartyAroundPosition(memberRoster, prisonerRoster, position, spawnRadius, 0f);

            mobileParty.Aggressiveness = 0.9f + 0.1f * (float)Owner.GetTraitLevel(DefaultTraits.Valor) - 0.05f * (float)Owner.GetTraitLevel(DefaultTraits.Mercy);
            //mobileParty.ItemRoster.Add(new ItemRosterElement(DefaultItems.Grain, MBRandom.RandomInt(15, 30)));
            //mobileParty.ItemRoster.Add(new ItemRosterElement)

            Owner.PassedTimeAtHomeSettlement = (int)(MBRandom.RandomFloat * 100f);
            
            if (spawnSettlement != null)
            {
                mobileParty.Ai.SetAIState(AIState.VisitingNearbyTown);
                mobileParty.SetMoveGoToSettlement(spawnSettlement);
            }
            mobileParty.Ai.SetAIState(AIState.VisitingVillage);
           
        }
    }

    
    public class ManhunterPartySaveDefiner : SaveableTypeDefiner
    {
        public ManhunterPartySaveDefiner() : base(2_543_135)
        {
        }

        protected override void DefineClassTypes()
        {
            base.DefineClassTypes();
            AddClassDefinition(typeof(ManhunterPartyComponent), 1);
        }

        protected override void DefineContainerDefinitions()
        {
            base.DefineContainerDefinitions();
            ConstructContainerDefinition(typeof(List<ManhunterPartyComponent>));
        }
    }
}
